//! The five representative lifecycle states.
//!
//! Each scenario builds the same three-contract deployment from the same
//! synthetic inputs and then advances it to one state. The inputs are chosen
//! for reviewability, not realism: identifier hashes are repeated single bytes,
//! ledger time starts at a round number, and every address is generated by the
//! test environment. Nothing here has ever existed on a real network.

use soroban_sdk::testutils::{Address as _, Events as _, Ledger as _};
use soroban_sdk::xdr::ContractEvent;
use soroban_sdk::{Address, BytesN, Env};

use issuer_registry::{IssuerRegistryContract, IssuerRegistryContractClient};
use proof_registry::{ProofRegistryContract, ProofRegistryContractClient};
use protocol_config::{ProtocolConfigContract, ProtocolConfigContractClient};

use super::render::Aliases;

/// Ledger sequence and timestamp every scenario starts from.
pub const GENESIS_SEQUENCE: u32 = 1_000;
pub const GENESIS_TIMESTAMP: u64 = 1_000;

/// Timestamp the proof in the `expired` scenario passes.
pub const PROOF_EXPIRES_AT: u64 = 2_000;

pub const SCHEMA_VERSION: u32 = 1;

/// Identifier bytes. Single repeated bytes so a fixture reader can tell one
/// identifier from another at a glance.
pub const ISSUER_ID: u8 = 0x11;
pub const ISSUER_METADATA: u8 = 0x22;
pub const PROOF_ID: u8 = 0x33;
pub const PROOF_COMMITMENT: u8 = 0x44;

/// Every scenario this crate snapshots, in fixture order.
pub const SCENARIOS: [&str; 5] = ["initialized", "active", "paused", "revoked", "expired"];

pub struct Scenario {
    pub env: Env,
    pub aliases: Aliases,
    pub contracts: std::vec::Vec<(&'static str, Address)>,
    /// Ledger sequence and timestamp the snapshot was taken at. Explicitly set
    /// by every scenario, so it is deterministic context rather than host
    /// metadata, and it is what makes the expired state legible.
    pub ledger: (u32, u64),
    /// Verdicts the read-only entry points return in this state. Storage says
    /// what is recorded; these say what a verifier concludes from it.
    pub verdicts: std::vec::Vec<(&'static str, bool)>,
    events: std::vec::Vec<ContractEvent>,
}

impl Scenario {
    /// Events emitted over the whole scenario, in emission order and in the
    /// XDR form an indexer receives.
    pub fn events(&self) -> &[ContractEvent] {
        &self.events
    }
}

/// Accumulates the event log across a scenario.
///
/// `env.events().all()` reports the events of the **most recent invocation**
/// rather than an accumulated log, so a later call replaces what an earlier one
/// published. Reading immediately after each call is the only way to build a
/// complete, correctly ordered log.
struct Recorder {
    events: std::vec::Vec<ContractEvent>,
}

impl Recorder {
    fn new() -> Self {
        Self {
            events: std::vec::Vec::new(),
        }
    }

    fn after(&mut self, env: &Env, call: impl FnOnce()) {
        call();
        self.events
            .extend(env.events().all().events().iter().cloned());
    }
}

fn bytes32(env: &Env, value: u8) -> BytesN<32> {
    BytesN::from_array(env, &[value; 32])
}

/// Builds the named scenario, or panics if the name is not one of
/// [`SCENARIOS`].
pub fn build(name: &str) -> Scenario {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_sequence_number(GENESIS_SEQUENCE);
    env.ledger().set_timestamp(GENESIS_TIMESTAMP);

    let admin = Address::generate(&env);
    let issuer = Address::generate(&env);

    let config_id = env.register(ProtocolConfigContract, ());
    let config = ProtocolConfigContractClient::new(&env, &config_id);
    let issuers_id = env.register(IssuerRegistryContract, ());
    let issuers = IssuerRegistryContractClient::new(&env, &issuers_id);
    let proofs_id = env.register(ProofRegistryContract, ());
    let proofs = ProofRegistryContractClient::new(&env, &proofs_id);

    let mut aliases = Aliases::new();
    aliases.insert(&admin, "admin");
    aliases.insert(&issuer, "issuer");
    aliases.insert(&config_id, "protocol-config");
    aliases.insert(&issuers_id, "issuer-registry");
    aliases.insert(&proofs_id, "proof-registry");

    let mut recorder = Recorder::new();

    // --- initialized: provisioned, holding no records -----------------------
    recorder.after(&env, || config.initialize(&admin));
    recorder.after(&env, || config.approve_schema_version(&SCHEMA_VERSION));
    recorder.after(&env, || issuers.initialize(&admin));
    recorder.after(&env, || proofs.initialize(&admin, &issuers_id, &config_id));

    if name != "initialized" {
        // --- active: one issuer, one valid proof ---------------------------
        recorder.after(&env, || {
            issuers.register_issuer(
                &bytes32(&env, ISSUER_ID),
                &issuer,
                &bytes32(&env, ISSUER_METADATA),
            )
        });
        recorder.after(&env, || {
            proofs.register_proof(
                &bytes32(&env, PROOF_ID),
                &bytes32(&env, PROOF_COMMITMENT),
                &issuer,
                &SCHEMA_VERSION,
                &PROOF_EXPIRES_AT,
            )
        });
    }

    match name {
        "initialized" | "active" => {}
        // --- paused: the emergency brake engaged ---------------------------
        "paused" => recorder.after(&env, || config.pause()),
        // --- revoked: both terminal states reached -------------------------
        "revoked" => {
            recorder.after(&env, || proofs.revoke_proof(&bytes32(&env, PROOF_ID)));
            recorder.after(&env, || issuers.revoke_issuer(&bytes32(&env, ISSUER_ID)));
        }
        // --- expired: ledger time past the proof expiration ----------------
        //
        // The record is untouched; only the clock moved. That is the state a
        // verifier meets most often and the one most likely to be mishandled,
        // so it gets its own fixture.
        "expired" => env.ledger().set_timestamp(PROOF_EXPIRES_AT + 1),
        other => std::panic!("unknown scenario {other}"),
    }

    let has_records = name != "initialized";
    let verdicts = std::vec![
        ("protocol-config.is_paused", config.is_paused()),
        (
            "protocol-config.is_schema_version_approved(1)",
            config.is_schema_version_approved(&SCHEMA_VERSION),
        ),
        (
            "issuer-registry.is_active_address(issuer)",
            has_records && issuers.is_active_address(&issuer),
        ),
        (
            "proof-registry.is_valid_proof(proof)",
            has_records && proofs.is_valid_proof(&bytes32(&env, PROOF_ID)),
        ),
        (
            "proof-registry.is_revoked(proof)",
            has_records && proofs.is_revoked(&bytes32(&env, PROOF_ID)),
        ),
    ];

    let ledger = (env.ledger().sequence(), env.ledger().timestamp());

    Scenario {
        env,
        aliases,
        ledger,
        verdicts,
        contracts: std::vec![
            ("protocol-config", config_id),
            ("issuer-registry", issuers_id),
            ("proof-registry", proofs_id),
        ],
        events: recorder.events,
    }
}
